version: '3'
services:
  db:
    image: postgres:14
    container_name: db
    # networks:
    #   - net
    environment:
      POSTGRES_USER: privy
      POSTGRES_DB: privy
      POSTGRES_PASSWORD: pa55w0rdprivy
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  nodejs:
    image: node:latest
    depends_on:
      - middleware
    build:
      context: .
      dockerfile: ./node-app/Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    # networks:
    #   - net
    restart: always

  middleware:
    build:
      context: .
      dockerfile: ./go-app/Dockerfile
    ports:
      - "80:9001"
    depends_on:
      - db
    restart: always
    # networks:
    #   - net
    environment:
      APP_PORT: 9001
      APP_NAME: Privy
      DB_DSN: postgres://privy:pa55w0rdprivy@db:5432/privy
      DB_NAME: privy
      DB_MAX_OPEN_CONN: 4
      DB_MAX_IDLE_CONN: 20
      DB_MAX_LIFE_CONN: 3
      JWT_VERIFYKEY: ""
      JWT_SIGNATURE: rahmanteja
      JWT_EXPIRATION: 3600
      JWT_AUD: "icon-plus"
      JWT_ISS: icon-plus
      REFRESH_JWT_VERIFYKEY: ""
      REFRESH_JWT_SIGNATURE: rahmanteja
      REFRESH_JWT_EXPIRATION: 3600
      REFRESH_JWT_AUD: "icon-plus"
      REFRESH_JWT_ISS: icon-plus
      IS_REDIS: 0
      REDIS_ADDR: ""
      REDIS_PWD: ""
      REDIS_DB: ""
      BASIC_AUTH_USERNAME: pR1vY
      BASIC_AUTH_PASSWORD: pa55w0rd@pR1vY
      PRIVY_HOST: https://8113915-sb1.suitetalk.api.netsuite.com
      PRIVY_USERNAME: d0e9d94e53648143208032f312cbe8c47cfa1a2084228114bcb4e2ce397f8704
      PRIVY_PASSWORD: bc5627d9c0d2860d689a11243a73d7eab8f11f101d6f7e2eaa5fff5cfe28f82e
      ACZD_BASE: http://apergu.tech:9002/
      ERP_PRIVY_USERNAME: apergu
      ERP_PRIVY_PASSWORD: "2dp$m48k#ut9"
      ERP_PRIVY_APPLICATION_KEY: VUNSAT9GP6e5Rc7qv8ZDnh
      ERP_PRIVY_REQUEST_ID: 7c7bab49266d3529254f2532fe7cff8e
    links:
      - db
  # apache2:
  #   image: httpd:latest
  #   ports:
  #     - "80:8080"
  #   volumes:
  #     - ./apache2/apergu.tech.conf:/etc/apache2/sites-available/apergu.tech.conf
  #   depends_on:
  #     - middleware
  #   links:
  #     - middleware

volumes:
  db-data:

    # networks:
    #   net:
    #     driver: bridge







# 
version: '3.8'

services:
  privy-nodejs-jwt:
    image: apergudev/privy-nodejs-jwt
    container_name: privy-nodejs-jwt
    ports:
      - "3000:3000"
    restart: unless-stopped

  privy-middleware:
    image: apergudev/privy-middleware
    container_name: privy-middleware
    ports:
      - "9001:9001"
    environment:
      APP_NAME: Privy
      DB_DSN: postgres://privy:pa55w0rdprivy@db:5432/privy
      DB_NAME: privy
      DB_MAX_OPEN_CONN: 4
      DB_MAX_IDLE_CONN: 20
      DB_MAX_LIFE_CONN: 3
      BASIC_AUTH_USERNAME: pR1vY
      BASIC_AUTH_PASSWORD: pa55w0rd@pR1vY
      PRIVY_HOST: https://8113915-sb1.suitetalk.api.netsuite.com
      PRIVY_USERNAME: d0e9d94e53648143208032f312cbe8c47cfa1a2084228114bcb4e2ce397f8704
      PRIVY_PASSWORD: bc5627d9c0d2860d689a11243a73d7eab8f11f101d6f7e2eaa5fff5cfe28f82e
      ACZD_BASE: http://apergu.tech:9002/
      ERP_PRIVY_USERNAME: apergu
      ERP_PRIVY_PASSWORD: "2dp$m48k#ut9"
      ERP_PRIVY_APPLICATION_KEY: VUNSAT9GP6e5Rc7qv8ZDnh
      ERP_PRIVY_REQUEST_ID: 7c7bab49266d3529254f2532fe7cff8e
    depends_on:
      - postgres-db
    restart: unless-stopped

  privy-aczd-module:
    image: apergudev/privy-aczd-module
    container_name: privy-aczd-module
    ports:
      - "9002:9002"
    restart: unless-stopped

  kong:
    image: kong
    container_name: kong
    ports:
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"        # Running Kong in DB-less mode
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/kong.yml"
    volumes:
      - ./kong.yml:/usr/local/kong/kong.yml
    restart: unless-stopped
