version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: privy,
      POSTGRES_PASSWORD: p@$$w0rdprivy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Your Go application service
  privy-project:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_DSN: postgres://postgres:p@$$w0rdprivy@postgres:5432/privy

  # Apache web server
  apache:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./apache-config:/usr/local/apache2/conf

volumes:
  postgres-data:
