version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: privy
      POSTGRES_PASSWORD: p@$$w0rdprivy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Your Go application service
  privy-project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - project-privy_default
    environment:
      DB_DSN: postgres://postgres:p@$$w0rdprivy@localhost:5432/privy

volumes:
  postgres-data:


networks:
  project-privy_default:
    # driver: bridge
    external: true
